version: "3.8"
services:
  mysql:
    image: mysql:8.0.26
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
  server:
    build:
      dockerfile: .docker/server/Dockerfile
      context: .
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: .
        target: /server
    command: yarn server
    depends_on:
      - mysql

